# Base prototypes can be found in \Resources\Prototypes\Recipes\Lathes\security.yml

# Recipes

- type: latheRecipe
  id: ClothingEyesVision
  result: ClothingEyesVision
  completetime: 5
  materials:
    Steel: 300
    Glass: 100
    Plastic: 200

- type: latheRecipe
  id: ClothingEyesVisionSec
  result: ClothingEyesVisionSec
  completetime: 5
  materials:
    Steel: 300
    Glass: 100
    Plastic: 200
