using System.Collections.Generic;
using Content.Shared._Horizon.EventItems;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Prototypes;

namespace Content.Client._Horizon.EventItems;

[GenerateTypedNameReferences]
public sealed partial class EventItemsTab : BoxContainer
{
    [Dependency] private readonly IPrototypeManager _protoManager = default!;
    [Dependency] private readonly IEntityManager _entManager = default!;

    private SpriteSystem? _spriteSystem;

    public EventItemsTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _spriteSystem = _entManager.System<SpriteSystem>();
    }

    /// <summary>
    /// Requests the server to send the event items for the current player.
    /// </summary>
    public void RequestItems()
    {
        var system = _entManager.System<EventItemsUISystem>();
        system.RequestItems();
    }

    /// <summary>
    /// Updates the displayed items.
    /// </summary>
    public void UpdateItems(List<EventItemData> items)
    {
        ItemsContainer.RemoveAllChildren();

        NoItemsLabel.Visible = items.Count == 0;

        foreach (var item in items)
        {
            var control = new EventItemControl();
            control.SetData(item, _protoManager, _spriteSystem);
            control.OnToggled += OnItemToggled;
            ItemsContainer.AddChild(control);
        }
    }

    private void OnItemToggled(int itemId, bool enabled)
    {
        var system = _entManager.System<EventItemsUISystem>();
        system.ToggleItem(itemId, enabled);
    }
}
