using System;
using Content.Shared._Horizon.EventItems;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Horizon.EventItems;

[GenerateTypedNameReferences]
public sealed partial class EventItemControl : PanelContainer
{
    public event Action<int, bool>? OnToggled;

    private int _itemId;

    public EventItemControl()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetData(EventItemData data, IPrototypeManager protoManager, SpriteSystem? spriteSystem)
    {
        _itemId = data.Id;

        var displayName = data.CustomName ?? data.PrototypeId;
        if (protoManager.TryIndex<EntityPrototype>(data.PrototypeId, out var proto))
        {
            displayName = data.CustomName ?? proto.Name;
        }

        ItemNameLabel.Text = displayName;
        ItemDescLabel.Text = data.CustomDescription ?? proto?.Description ?? string.Empty;
        ItemCostLabel.Text = Loc.GetString("event-item-item-cost", ("cost", data.CreditCost));
        ItemGrantedByLabel.Text = Loc.GetString("event-item-item-granted-by", ("admin", data.GrantedBy));

        ToggleButton.Pressed = data.IsEnabled;
        ToggleButton.Text = data.IsEnabled
            ? Loc.GetString("event-item-item-enabled")
            : Loc.GetString("event-item-item-disabled");

        ToggleButton.OnToggled += OnTogglePressed;

        // Try to set the icon from the prototype
        if (proto != null && spriteSystem != null)
        {
            ItemIcon.Texture = spriteSystem.GetPrototypeIcon(proto).Default;
        }
    }

    private void OnTogglePressed(BaseButton.ButtonToggledEventArgs args)
    {
        ToggleButton.Text = args.Pressed
            ? Loc.GetString("event-item-item-enabled")
            : Loc.GetString("event-item-item-disabled");

        OnToggled?.Invoke(_itemId, args.Pressed);
    }
}
