using System;
using Content.Shared._Horizon.EventItems;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client._Horizon.EventItems;

[GenerateTypedNameReferences]
public sealed partial class EventItemControl : PanelContainer
{
    public event Action<int, bool>? OnToggled;

    private int _itemId;

    // Card colors for enabled/disabled states
    private static readonly Color EnabledBg = Color.FromHex("#1a3a2a60");
    private static readonly Color EnabledBorder = Color.FromHex("#3a7a5a80");
    private static readonly Color DisabledBg = Color.FromHex("#1a2a3a60");
    private static readonly Color DisabledBorder = Color.FromHex("#3a5a7a80");

    public EventItemControl()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetData(EventItemData data, IPrototypeManager protoManager, SpriteSystem? spriteSystem)
    {
        _itemId = data.Id;

        var displayName = data.CustomName ?? data.PrototypeId;
        EntityPrototype? proto = null;
        if (protoManager.TryIndex<EntityPrototype>(data.PrototypeId, out proto))
        {
            displayName = data.CustomName ?? proto.Name;
        }

        ItemNameLabel.Text = displayName;
        ItemDescLabel.Text = data.CustomDescription ?? proto?.Description ?? string.Empty;
        ItemCostLabel.Text = Loc.GetString("event-item-item-cost", ("cost", data.CreditCost));
        ItemGrantedByLabel.Text = Loc.GetString("event-item-item-granted-by", ("admin", data.GrantedBy));

        ToggleButton.Pressed = data.IsEnabled;
        UpdateToggleVisuals(data.IsEnabled);

        ToggleButton.OnToggled += OnTogglePressed;

        // Try to set the icon from the prototype
        if (proto != null && spriteSystem != null)
        {
            ItemIcon.Texture = spriteSystem.GetPrototypeIcon(proto).Default;
        }
    }

    private void OnTogglePressed(BaseButton.ButtonToggledEventArgs args)
    {
        UpdateToggleVisuals(args.Pressed);
        OnToggled?.Invoke(_itemId, args.Pressed);
    }

    private void UpdateToggleVisuals(bool enabled)
    {
        ToggleButton.Text = enabled
            ? Loc.GetString("event-item-item-enabled")
            : Loc.GetString("event-item-item-disabled");

        // Update card background color based on state
        if (CardBackground.PanelOverride is StyleBoxFlat styleBox)
        {
            styleBox.BackgroundColor = enabled ? EnabledBg : DisabledBg;
            styleBox.BorderColor = enabled ? EnabledBorder : DisabledBorder;
        }
    }
}
