using System;
using System.Collections.Generic;
using System.Numerics;
using Content.Shared._Horizon.EventItems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Horizon.EventItems;

[GenerateTypedNameReferences]
public sealed partial class GrantEventItemWindow : DefaultWindow
{
    public event Action<Guid, int>? OnConfirm;

    private List<EventItemPlayerInfo> _players = new();
    private EventItemPlayerInfo? _selectedPlayer;

    public GrantEventItemWindow()
    {
        MinSize = SetSize = new Vector2(400, 400);
        RobustXamlLoader.Load(this);

        CreditCostSpinBox.Value = 0;
        ConfirmButton.OnPressed += OnConfirmPressed;
        PlayerSearchBar.OnTextChanged += OnSearchChanged;
        PlayerList.OnItemSelected += OnPlayerSelected;
        PlayerList.OnItemDeselected += _ => _selectedPlayer = null;
    }

    public void UpdateState(GrantEventItemEuiState state)
    {
        ItemNameLabel.Text = Loc.GetString("event-item-grant-item-name", ("name", state.EntityName));
        ItemDescLabel.Text = Loc.GetString("event-item-grant-item-desc", ("desc", state.EntityDescription));
        ItemProtoLabel.Text = Loc.GetString("event-item-grant-item-proto", ("proto", state.PrototypeId));

        _players = state.OnlinePlayers;
        PopulatePlayerList(string.Empty);
    }

    private void PopulatePlayerList(string filter)
    {
        PlayerList.Clear();
        _selectedPlayer = null;

        foreach (var player in _players)
        {
            var displayName = $"{player.UserName} ({player.CharacterName})";
            if (!string.IsNullOrEmpty(filter) &&
                !displayName.Contains(filter, StringComparison.OrdinalIgnoreCase))
                continue;

            var item = PlayerList.AddItem(displayName);
            item.Metadata = player;
        }
    }

    private void OnSearchChanged(LineEdit.LineEditEventArgs args)
    {
        PopulatePlayerList(args.Text);
    }

    private void OnPlayerSelected(ItemList.ItemListSelectedEventArgs args)
    {
        var item = PlayerList[args.ItemIndex];
        _selectedPlayer = item.Metadata as EventItemPlayerInfo;
    }

    private void OnConfirmPressed(BaseButton.ButtonEventArgs args)
    {
        if (_selectedPlayer == null)
            return;

        OnConfirm?.Invoke(_selectedPlayer.UserId, CreditCostSpinBox.Value);
    }
}
