using Content.Shared._Horizon.FlavorText;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.FlavorText
{
    [GenerateTypedNameReferences]
    public sealed partial class FlavorText : Control
    {
        public Action<string>? OnFlavorTextChanged;

        // Horizon start
        public Action<int>? OnErpStatChanged;
        public Action<int>? OnFactionChanged;
        // Horizon end

        public FlavorText()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            var loc = IoCManager.Resolve<ILocalizationManager>();
            CFlavorTextInput.Placeholder = new Rope.Leaf(loc.GetString("flavor-text-placeholder"));
            CFlavorTextInput.OnTextChanged += _ => FlavorTextChanged();

            // Horizon start
            ERPStatusButton.OnItemSelected += args => OnErpStatChanged?.Invoke(args.Id);
            FactionButton.OnItemSelected += args => OnFactionChanged?.Invoke(args.Id);
            // Horizon end
        }

        public void FlavorTextChanged()
        {
            OnFlavorTextChanged?.Invoke(Rope.Collapse(CFlavorTextInput.TextRope).Trim());
        }
    }
}
