using Content.Client.UserInterface.Controls;
using Content.Shared._Horizon._Fractions.AnCo.CurrencyExchange;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Horizon._Fractions.AnCo.CurrencyExchange;

[GenerateTypedNameReferences]
public sealed partial class CurrencyExchangeMenu : FancyWindow
{
    private CurrencyExchangeBoundUserInterface? _owner;
    private CurrencyExchangeBoundUserInterfaceState? _lastState;

    public CurrencyExchangeMenu()
    {
        RobustXamlLoader.Load(this);

        ExchangeButton.OnPressed += _ => OnExchangePressed();
        ExchangeAllButton.OnPressed += _ => OnExchangeAllPressed();
        AmountEdit.OnTextChanged += _ => UpdateWillReceive();
    }

    public void SetOwner(CurrencyExchangeBoundUserInterface owner)
    {
        _owner = owner;
    }

    public void UpdateState(CurrencyExchangeBoundUserInterfaceState state)
    {
        _lastState = state;

        // Rate display
        RateLabel.Text = $"{state.CurrentExchangeRate:F2}x";
        RateLabel.ModulateSelfOverride = GetRateColor(state.CurrentExchangeRate);

        // Trend indicator
        TrendLabel.Text = state.RateTrend switch
        {
            > 0 => "↑",
            < 0 => "↓",
            _ => "→"
        };
        TrendLabel.ModulateSelfOverride = state.RateTrend switch
        {
            > 0 => Color.LimeGreen,
            < 0 => Color.Red,
            _ => Color.Yellow
        };

        // Commission
        CommissionLabel.Text = $"{state.Commission * 100:F0}%";

        // Disk info
        if (state.HasDisk)
        {
            DiskCreditsLabel.Text = $"{state.DiskCredits} / {state.DiskMaxCredits}";
            DiskFillBar.Value = state.DiskMaxCredits > 0 ? (float)state.DiskCredits / state.DiskMaxCredits : 0;
            DiskFillBar.ModulateSelfOverride = Color.Cyan;
            NoDiskLabel.Visible = false;
            ExchangeButton.Disabled = state.DiskCredits <= 0;
            ExchangeAllButton.Disabled = state.DiskCredits <= 0;
            AmountEdit.Editable = state.DiskCredits > 0;
        }
        else
        {
            DiskCreditsLabel.Text = Loc.GetString("currency-exchange-no-disk-short");
            DiskFillBar.Value = 0;
            NoDiskLabel.Visible = true;
            ExchangeButton.Disabled = true;
            ExchangeAllButton.Disabled = true;
            AmountEdit.Editable = false;
        }

        UpdateWillReceive();
    }

    private void UpdateWillReceive()
    {
        if (_lastState == null || !_lastState.HasDisk)
        {
            WillReceiveLabel.Text = "0";
            return;
        }

        if (!int.TryParse(AmountEdit.Text, out var amount) || amount <= 0)
        {
            WillReceiveLabel.Text = "0";
            return;
        }

        amount = Math.Min(amount, _lastState.DiskCredits);
        var gross = (int)(amount * _lastState.CurrentExchangeRate);
        var commission = (int)(gross * _lastState.Commission);
        var net = gross - commission;

        WillReceiveLabel.Text = $"{net} ({Loc.GetString("currency-exchange-commission-deducted", ("amount", commission))})";
    }

    private void OnExchangePressed()
    {
        if (_owner == null || _lastState == null || !_lastState.HasDisk)
            return;

        if (!int.TryParse(AmountEdit.Text, out var amount) || amount <= 0)
            return;

        amount = Math.Min(amount, _lastState.DiskCredits);
        _owner.SendExchange(amount);
    }

    private void OnExchangeAllPressed()
    {
        if (_owner == null || _lastState == null || !_lastState.HasDisk || _lastState.DiskCredits <= 0)
            return;

        _owner.SendExchangeAll();
    }

    private static Color GetRateColor(float rate)
    {
        return rate switch
        {
            >= 1.5f => Color.LimeGreen,
            >= 1.2f => Color.Green,
            >= 0.8f => Color.Yellow,
            >= 0.6f => Color.Orange,
            _ => Color.Red
        };
    }
}
