using Content.Client.UserInterface.Controls;
using Content.Shared._Horizon._Fractions.AnCo.Cryptominer;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Horizon._Fractions.AnCo.Cryptominer;

[GenerateTypedNameReferences]
public sealed partial class AnCoCryptominerMenu : FancyWindow
{
    private readonly AnCoCryptominerBoundUserInterface _owner;

    public AnCoCryptominerMenu(AnCoCryptominerBoundUserInterface owner)
    {
        RobustXamlLoader.Load(this);

        _owner = owner;

        ToggleButton.OnPressed += _ =>
        {
            _owner.SendToggle();
        };
    }

    public void UpdateState(CryptominerBoundUserInterfaceState state)
    {
        // Update status label with color based on state
        StatusLabel.Text = GetStateText(state.State);
        StatusLabel.ModulateSelfOverride = GetStateColor(state.State);

        // Update temperature display
        TemperatureLabel.Text = $"{state.CurrentTemperature:F1} K ({state.CurrentTemperature - 273.15f:F1} °C)";

        // Update efficiency
        EfficiencyLabel.Text = $"{state.Efficiency * 100:F0}%";

        // Update credits info (per-minute, with current efficiency)
        var effectiveCreditsPerMinute = (int)(state.CreditsPerMinute * state.Efficiency);
        CreditsPerSecondLabel.Text = $"{effectiveCreditsPerMinute}";

        // Update power
        PowerLabel.Text = state.IsPowered
            ? $"{state.PowerConsumption:F0} W"
            : Loc.GetString("cryptominer-window-no-power");

        // Update temperature bar (normalized between 293K and critical temp)
        var minTemp = 293.15f; // Room temperature
        var range = state.CriticalTemperature - minTemp;
        var normalizedTemp = range > 0.001f
            ? (state.CurrentTemperature - minTemp) / range
            : 0f;
        TemperatureBar.Value = Math.Clamp(normalizedTemp, 0f, 1f);

        // Color the temperature bar based on state
        TemperatureBar.ModulateSelfOverride = GetStateColor(state.State);

        // Update toggle button text
        var isOff = state.State == CryptominerState.Off ||
                    state.State == CryptominerState.NoAtmosphere ||
                    state.State == CryptominerState.NoDisks;
        ToggleButton.Text = isOff
            ? Loc.GetString("cryptominer-window-toggle-on")
            : Loc.GetString("cryptominer-window-toggle-off");

        ToggleButton.Disabled = !state.IsPowered;
    }

    private static string GetStateText(CryptominerState state)
    {
        return state switch
        {
            CryptominerState.Off => Loc.GetString("cryptominer-state-off"),
            CryptominerState.Normal => Loc.GetString("cryptominer-state-normal"),
            CryptominerState.Warning => Loc.GetString("cryptominer-state-warning"),
            CryptominerState.Overheat => Loc.GetString("cryptominer-state-overheat"),
            CryptominerState.Critical => Loc.GetString("cryptominer-state-critical"),
            CryptominerState.NoAtmosphere => Loc.GetString("cryptominer-state-no-atmosphere"),
            CryptominerState.NoDisks => Loc.GetString("cryptominer-state-no-disks"),
            _ => Loc.GetString("cryptominer-state-unknown")
        };
    }

    private static Color GetStateColor(CryptominerState state)
    {
        return state switch
        {
            CryptominerState.Off => Color.Gray,
            CryptominerState.Normal => Color.Green,
            CryptominerState.Warning => Color.Yellow,
            CryptominerState.Overheat => Color.Orange,
            CryptominerState.Critical => Color.Red,
            CryptominerState.NoAtmosphere => Color.Cyan,
            CryptominerState.NoDisks => Color.Purple,
            _ => Color.White
        };
    }
}
