## Static recipes
## Dynamic recipes

- type: latheRecipePack
  id: NightVisionPack
  recipes:
  - ClothingEyesVision

- type: latheRecipePack
  id: NightVisionSecPack
  recipes:
  - ClothingEyesVisionSec

- type: latheRecipePack
  id: WeaponModulesPack
  recipes:
  - AttachmentVerticalGrip
  - AttachmentLaserSight
  - AttachmentReflexSight
  - AttachmentT2Miniscope
  - AttachmentM90UnderbarrelShotgun
  - AttachmentM90GrenadeLauncher
  - AttachmentMagneticHarness
  - AttachmentSuppressor
  - AttachmentAntiLyingWarrior
  - 40mmGrenadeBaton
  - 40mmGrenadeEMP
  - 40mmGrenadeFlash
  - 40mmGrenadeSmoke
