using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Systems.Guidebook;
using Content.Shared.Guidebook;
using Content.Shared.Silicons.Borgs;
using Content.Shared.Silicons.Borgs.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Silicons.Borgs;

/// <summary>
/// Menu used by borgs to select their type.
/// </summary>
/// <seealso cref="BorgSelectTypeUserInterface"/>
/// <seealso cref="BorgSwitchableTypeComponent"/>
[GenerateTypedNameReferences]
public sealed partial class BorgSelectTypeMenu : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntityManager _entMan = default!;    // Horizon
    private readonly BorgSwitchableTypeSystem _borg;

    private BorgTypePrototype? _selectedBorgType;
    private int _selectedSkin;  // Horizon borg skins

    public event Action<ProtoId<BorgTypePrototype>, int>? ConfirmedBorgType;    // Horizon borg skins

    [ValidatePrototypeId<GuideEntryPrototype>]
    private static readonly List<ProtoId<GuideEntryPrototype>> GuidebookEntries = new() { "Cyborgs", "Robotics" };

    public BorgSelectTypeMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _borg = _entMan.System<BorgSwitchableTypeSystem>(); // Horizon

        var group = new ButtonGroup();
        foreach (var borgType in _prototypeManager.EnumeratePrototypes<BorgTypePrototype>().OrderBy(PrototypeName))
        {
            var button = new Button
            {
                Text = PrototypeName(borgType),
                Group = group,
            };
            button.OnPressed += _ =>
            {
                _selectedBorgType = borgType;
                UpdateInformation(borgType);
            };
            SelectionsContainer.AddChild(button);
        }

        ConfirmTypeButton.OnPressed += ConfirmButtonPressed;
        HelpGuidebookIds = GuidebookEntries;
    }

    private void UpdateInformation(BorgTypePrototype prototype)
    {
        _selectedBorgType = prototype;

        InfoContents.Visible = true;
        InfoPlaceholder.Visible = false;
        ConfirmTypeButton.Disabled = false;

        NameLabel.Text = PrototypeName(prototype);
        DescriptionLabel.Text = Loc.GetString($"borg-type-{prototype.ID}-desc");
        ChassisView.SetPrototype(prototype.DummyPrototype);

        // Horizon start
        var group = new ButtonGroup(false);
        SkinsContainer.RemoveAllChildren();
        for (var i = 0; i < prototype.Skins.Count; i++)
        {
            SpriteView sprite = new()
            {
                Scale = new(2),
                SetSize = new(48),
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center
            };

            var ent = _entMan.Spawn(prototype.DummyPrototype);
            var comp = _entMan.EnsureComponent<BorgSwitchableTypeComponent>(ent);
            comp.SelectedBorgSkin = prototype.Skins[i];
            _borg.UpdateEntityAppearance((ent, comp), prototype);

            sprite.SetEntity(ent);

            Button button = new()
            {
                SetSize = new(72, 64),
                Group = group,
                ToolTip = Loc.GetString(prototype.Skins[i].Name),
                Margin = new(8, 4),
                Children = { sprite }
            };

            var idx = i;
            button.OnPressed += args => _selectedSkin = idx;

            SkinsContainer.AddChild(button);
        }
        // Horizon end
    }

    private void ConfirmButtonPressed(BaseButton.ButtonEventArgs obj)
    {
        if (_selectedBorgType == null)
            return;

        ConfirmedBorgType?.Invoke(_selectedBorgType, _selectedSkin);    // Horizon borg skins
    }

    private static string PrototypeName(BorgTypePrototype prototype)
    {
        return Loc.GetString($"borg-type-{prototype.ID}-name");
    }
}
