using Content.Client.Message;
using Content.Shared._Horizon.Expeditions;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Horizon.Expeditions.Ui;

[GenerateTypedNameReferences]
public sealed partial class ExpeditionGoalOption : PanelContainer
{
    public event Action? ClaimPressed;

    public ExpeditionGoalOption(int idx, ExpeditionGoal goal, IEntityManager entMan)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        TitleStripe.Text = Loc.GetString("expeditions-goal-title-label", ("id", idx));

        DescriptionLabel.SetMarkup(goal.Description);
        RewardLabel.SetMarkup(Loc.GetString("expeditions-goal-reward-label", ("reward", goal.Reward), ("currency", goal.CurrencyStr)));
        Icon.SetEntity(entMan.Spawn(goal.IconEntity));

        LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);
        BigPanel.ModulateSelfOverride = new Color(30, 30, 34);

        ClaimButton.OnPressed += args => ClaimPressed?.Invoke();
    }
}
