using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared._Horizon.Expeditions;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Horizon.Expeditions.Ui;

[GenerateTypedNameReferences]
public sealed partial class ExpeditionGoalsConsoleMenu : FancyWindow,
    IComputerWindow<EmergencyConsoleBoundUserInterfaceState>
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    public TimeSpan NextOffer;
    public TimeSpan Cooldown = TimeSpan.FromMinutes(5);

    public Action<int>? OnOptionSelected;

    public ExpeditionGoalsConsoleMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Populate(Dictionary<int, ExpeditionGoal> options)
    {
        Container.DisposeAllChildren();

        foreach (var option in options)
        {
            var optionControl = new ExpeditionGoalOption(option.Key, option.Value, _entMan);
            optionControl.ClaimPressed += () => OnOptionSelected?.Invoke(option.Key);
            Container.AddChild(optionControl);
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var remaining = NextOffer - _timing.CurTime;

        if (remaining < TimeSpan.Zero)
        {
            NextOfferBar.Value = 1f;
            NextOfferText.Text = "00:00";
        }
        else
        {
            NextOfferBar.Value = 1f - (float)(remaining / Cooldown);
            NextOfferText.Text = $"{remaining.Minutes:00}:{remaining.Seconds:00}";
        }
    }
}
