using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Horizon._Fractions.AnCo.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class CompanionUiFragment : BoxContainer
{
    public CompanionUiFragment()
    {
        //RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
    }

    public void UpdateState()
    {

    }
}
