using System.Linq;
using System.Text;
using Content.Client.Actions;
using Content.Client.Message;
using Content.Shared._NF.Bank;
using Content.Shared.FixedPoint;
using Content.Shared.Store;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Content.Shared._Horizon.Cytology.Systems;
using Content.Client.GameTicking.Managers;
using Content.Shared.Store;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Chemistry;
using Content.Shared.Chemistry.Reagent;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System.Linq;
using System.Numerics;
using Content.Shared.FixedPoint;
using Robust.Client.Graphics;
using static Robust.Client.UserInterface.Controls.BoxContainer;
using Robust.Client.GameObjects;
using Content.Shared._Horizon.Cytology.Systems;


namespace Content.Client._Horizon.Cytology.Microscope.UI;

[GenerateTypedNameReferences]
public sealed partial class CellSemplesItemControl : Control
{
    public CellSemplesItemControl(CellSampleInfo info)
    {
        RobustXamlLoader.Load(this);

        DisplayName.Text = info.DisplayName;
        GrowthRateInSeconds.Text = info.GrowthRateInSeconds.ToString();
        ViralSusceptibility.Text = info.ViralSusceptibility.ToString();
        foreach (string item in info.RequiredChemicals)
        {
            RequiredChemicals.Text += item;
        }
        foreach (string item in info.SupplementaryChemicals)
        {
            SupplementaryChemicals.Text += item;
        }
        foreach (string item in info.SuppressiveChemicals)
        {
            SuppressiveChemicals.Text += item;
        }
    }
}
