using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Chemistry;
using Content.Shared.Chemistry.Reagent;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System.Linq;
using System.Numerics;
using Content.Shared.FixedPoint;
using Robust.Client.Graphics;
using static Robust.Client.UserInterface.Controls.BoxContainer;
using Robust.Client.GameObjects;
using Content.Shared._Horizon.Cytology.Systems;

namespace Content.Client._Horizon.Cytology.Microscope.UI;

[GenerateTypedNameReferences]
public sealed partial class MicroscopeWindow : FancyWindow
{
    public MicroscopeWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateState(MicroscopeBoundUserInterfaceState state)
    {

        CellSamplesList.DisposeAllChildren();

        if (state.CellSampleInfo == null || state.CellSampleInfo.Count == 0)
            return;

        foreach (var info in state.CellSampleInfo)
        {
            var item = new CellSampleItemsControl(info);
            CellSamplesList.AddChild(item);
        }
    }

}
