- type: entity
  parent: BaseMachineCircuitboard
  id: MachineBluespaceHarvesterCircuitboard
  components:
  - type: Sprite
    sprite: _Horizon/Bluespace/module.rsi
    state: bluespace
  - type: Item
    size: Normal
  - type: MachineBoard
    prototype: BluespaceHarvester
    requirements:
      Capacitor: 5
      MatterBin: 15
    stackRequirements:
      Glass: 15
      Steel: 15
      CableHV: 5
      Bluespace: 5

- type: entity
  parent: BaseMachineCircuitboard
  id: MachineBLESCircuitboard
  components:
  - type: Sprite
    sprite: Objects/Misc/module.rsi
    state: bluespacearray
  - type: Item
    size: Normal
  - type: MachineBoard
    prototype: BLES
    requirements:
      Capacitor: 30
    stackRequirements:
      Steel: 10
      CableHV: 30
      Bluespace: 5
