using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Aavikko.Medical.Surgery;

[GenerateTypedNameReferences]
public sealed partial class SurgeryWindow : DefaultWindow
{
    public SurgeryWindow() => RobustXamlLoader.Load(this);
}
