using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Aavikko.Medical.Surgery;

[GenerateTypedNameReferences]
public sealed partial class SurgeryStepButton : ChoiceControl
{
    public EntityUid Step { get; set; }

    public SurgeryStepButton() => RobustXamlLoader.Load(this);
}
